# Generated by Django 5.1.6 on 2025-04-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
